# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "bundler"
gem "cucumber"
gem "rest-client"
gem "test-unit"
gem "json", "~>2.1.0"
